// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD86KXotB9MYQBgX60Ml5CD09Sa8CamnCA',
    appId: '1:307435734074:web:00a3bbbd22bb396fe0a103',
    messagingSenderId: '307435734074',
    projectId: 'vapp-4deaa',
    authDomain: 'vapp-4deaa.firebaseapp.com',
    storageBucket: 'vapp-4deaa.appspot.com',
    measurementId: 'G-ZM60NBC11Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq96xc0H7YfYRKJe2jHnZPKv1PA_Y9c8o',
    appId: '1:307435734074:android:ecba2074963a0660e0a103',
    messagingSenderId: '307435734074',
    projectId: 'vapp-4deaa',
    storageBucket: 'vapp-4deaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwn9nx-brkcKnwtIlJOWEHQ8HNLf0fBY',
    appId: '1:307435734074:ios:b785af1e0082b333e0a103',
    messagingSenderId: '307435734074',
    projectId: 'vapp-4deaa',
    storageBucket: 'vapp-4deaa.appspot.com',
    iosBundleId: 'Cpp.edu.hikingEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXwn9nx-brkcKnwtIlJOWEHQ8HNLf0fBY',
    appId: '1:307435734074:ios:73d14d65ab97da3fe0a103',
    messagingSenderId: '307435734074',
    projectId: 'vapp-4deaa',
    storageBucket: 'vapp-4deaa.appspot.com',
    iosBundleId: 'Cpp.edu.hikingEvent.RunnerTests',
  );
}
